// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu3aVF2q7djPpp6oC1Zh7dyIo9_V4fIEw',
    appId: '1:383620890267:android:098a5941e292aeac87103e',
    messagingSenderId: '383620890267',
    projectId: 'bonus-cb975',
    storageBucket: 'bonus-cb975.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeVYa1MK9xWhiaIBEfDRO_a8zEL2RIFyI',
    appId: '1:383620890267:ios:d207d0ac2163238187103e',
    messagingSenderId: '383620890267',
    projectId: 'bonus-cb975',
    storageBucket: 'bonus-cb975.firebasestorage.app',
    iosBundleId: 'com.example.flutterUiClass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeVYa1MK9xWhiaIBEfDRO_a8zEL2RIFyI',
    appId: '1:383620890267:ios:d207d0ac2163238187103e',
    messagingSenderId: '383620890267',
    projectId: 'bonus-cb975',
    storageBucket: 'bonus-cb975.firebasestorage.app',
    iosBundleId: 'com.example.flutterUiClass',
  );
}
